REPO_TAGLINE: Software engineering • design patterns • quality
ASSETS_DIR: .github/readme
CTA_TEXT: Access the full course website
THEME: library
SITE_URL: https://academic-codex.github.io/SCE0611-Engenharia-De-Software

BG_1: "#1C1917"
BG_2: "#292524"
TEXT_MAIN: "#FAFAF9"
TEXT_MUTED: "#D6D3D1"
ACCENT: "#FB923C"
CARD_RADIUS: "18"