TITLE_1: SCE0611
TITLE_2: Engenharia de Software
SUBTITLE_1: Disciplina de graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro A …</li>
    <li>Artigo B …</li>
  </ul>

GITHUB_LINK: https://github.com/Academic-Codex/SCE0611-Engenharia-De-Software
HERO_FILE: engenharia-de-software.png